=== PritOnce/SAMOSA2/actividad25/actividad25.dtd
<!ELEMENT factura (empresa,fecha.emisión,datos.cliente,datos.facturas)>
<!ATTLIST factura nombre NMTOKEN #REQUIRED>
<!ELEMENT empresa (nom.empresa,calle.empresa,localidad.empresa,CIF.empresa,telf.empresa,fax.empresa)>
<!ELEMENT nom.empresa (#PCDATA)>
<!ELEMENT calle.empresa (#PCDATA)>
<!ELEMENT localidad.empresa (#PCDATA)>
<!ELEMENT CIF.empresa (#PCDATA)>
<!ELEMENT telf.empresa (#PCDATA)>
<!ELEMENT fax.empresa (#PCDATA)>
<!ELEMENT fecha.emisión (fecha,pedido,forma.pago)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT pedido (#PCDATA)>
<!ELEMENT forma.pago (#PCDATA)>
<!ELEMENT datos.cliente (num.cliente,nom.cliente,calle.envio,población.cliente,cod.postal,provincia)>
<!ELEMENT num.cliente (#PCDATA)>
<!ELEMENT nom.cliente (#PCDATA)>
<!ELEMENT calle.envio (#PCDATA)>
<!ELEMENT población.cliente (#PCDATA)>
<!ELEMENT cod.postal (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT datos.facturas (dato.facutura+,suma,total.factura)>
<!ELEMENT dato.facutura (REF,descripción,Cant,precio,I.V.A,importe)>
<!ELEMENT REF (#PCDATA)>
<!ELEMENT descripción (#PCDATA)>
<!ELEMENT Cant (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT I.V.A (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT suma (base.imponible,IVA,cuotaIVA)>
<!ELEMENT base.imponible (#PCDATA)>
<!ELEMENT IVA (#PCDATA)>
<!ELEMENT cuotaIVA (#PCDATA)>
<!ELEMENT total.factura (#PCDATA)>

=== PritOnce/SAMOSA2/actividad25/actividad25.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "actividad25.dtd">
<?xml-stylesheet type="text/xsl" href="actividad25.xsl"?>
<factura nombre="999">
    
    <empresa>
        <nom.empresa>Equipos Digitales S.L</nom.empresa>
        <calle.empresa>Av.Valladolid</calle.empresa>
        <localidad.empresa>Madrid 28015</localidad.empresa>
        <CIF.empresa>Q-9876543</CIF.empresa>
        <telf.empresa>91 777 66 99</telf.empresa>
        <fax.empresa>91 777 66 99</fax.empresa>
    </empresa>

    <fecha.emisión>
        <fecha>12-01-2005</fecha>
        <pedido>nº731</pedido>
        <forma.pago>EFECTIVO</forma.pago>
    </fecha.emisión>

    <datos.cliente>
        <num.cliente>879</num.cliente>
        <nom.cliente>Dario Bueno Gutiérrez</nom.cliente>
        <calle.envio>AV.Oporto nº7 4ºd</calle.envio>
        <población.cliente>Madrid</población.cliente>
        <cod.postal>28043</cod.postal>
        <provincia>Madrid</provincia>
    </datos.cliente>

    <datos.facturas>

        <dato.facutura>
            <REF>MII93000F/8</REF>
            <descripción>MICRO PENTIUM IV 3000MHZ FB800</descripción>
            <Cant>1</Cant>
            <precio>230 eur.</precio>
            <I.V.A>16.0</I.V.A>
            <importe>266.80 eur.</importe>
        </dato.facutura>

        <dato.facutura>
            <REF>MB8QDIP4</REF>
            <descripción>PLACA BASE QDI P4</descripción>
            <Cant>1</Cant>
            <precio>180 eur.</precio>
            <I.V.A>16.0</I.V.A>
            <importe>208.80 eur.</importe>
        </dato.facutura>

        <dato.facutura>
            <REF>MEDD512M32</REF>
            <descripción>DIMM DRR 512MB 3200</descripción>
            <Cant>2</Cant>
            <precio>40 eur.</precio>
            <I.V.A>16.0</I.V.A>
            <importe>92.80</importe>
        </dato.facutura>

        <dato.facutura>
            <REF>HD250GSA7</REF>
            <descripción>DISCO DURO 250GB S-ATA 7200</descripción>
            <Cant>4</Cant>
            <precio>120 eur.</precio>
            <I.V.A>16.0</I.V.A>
            <importe>556.80</importe>
        </dato.facutura>

        <suma>
            <base.imponible>970.00 eur.</base.imponible>
            <IVA>16.0</IVA>
            <cuotaIVA>155.20</cuotaIVA>
        </suma>
        <total.factura>1125.20 eur</total.factura>
    </datos.facturas>
</factura>
